### ISSUE TITLE
F7-vue synchronization

### ISSUE THREAD

**Issue by clarkdo** [pi0/nuxt7#10]
Hi @pi0, long time no see.
I took several days off to Thailand, now I'm back to work.
I have just raised 2 pull requests(https://github.com/framework7io/Framework7-Vue/pull/254, https://github.com/framework7io/Framework7-Vue/pull/255) and we can sync f7-vue repo after pr gets merged.

**Comment by pi0** [comment]
Hey. Hope you had a good trip :) Sure i will do that asap.

**Comment by clarkdo** [comment]
https://github.com/framework7io/Framework7-Vue/pull/254, https://github.com/framework7io/Framework7-Vue/pull/255 has been merged.
